name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: zareix/gh-actions/.github/workflows/docker.yml@main
    with:
      tag: latest
      push-image: true
      platforms: linux/amd64,linux/arm64
